version: "3.8"
services:
  mysql:
    image: mysql:8.0  
    container_name: sistema-hotel-mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  
      MYSQL_DATABASE: "sistema_hotel"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data:
